/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "lcd/screenDriver.h"
#include "general/mcuHeader.h"

int main(void)
{
    /* Loop forever */
	SystemInit();
	pinout();
	LCD_INIT();
	clearLCD();
	triangle t;
	t.p1 = (vec3){0.0f, 0.0f, 1.0f};
	t.p2 = (vec3){0.0f, 100.0f, 1.0f};
	t.p3 = (vec3){100.0f, 0.0f, 1.0f};
	addTriangle(t);
	projectTriangle(0);
	while(1){
	triangles[0].color = 0xFF;
	renderTriangle(0);
	}
	for(;;);
}
