/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "lcd/screenDriver.h"
#include "general/mcuHeader.h"
#include "lcd/model.h"

int main(void)
{
    /* Loop forever */
	SystemInit();
	pinout();
	LCD_INIT();
	changeBackdrop(0xFFFF);
	clearLCD_FULL();
	changeBackdrop(0x0000);
	//changeBackdrop(0xf000);
	//changeBackdrop(0x0);
	//triangle t;
	//t.p1 = (vec3){-10.0f, -10.0f, 10.0f};
	//t.p2 = (vec3){-10.0f, 200.0f, 1.0f};
	//t.p3 = (vec3){200.0f, -10.0f, 1.0f};
	//addTriangle(t);
	//addTriangle(t);
	//projectTriangle(1);
	//triangles[0].color = 0xFF;
	//triangles[1].color = 0x00FF;
	loadCube(0xF800);     // red cube
	loadPyramid(0x07E0);  // green pyramid
	loadColumn(0x001F);   // blue column
	setLightPos(-50.0f, 0.0f, -0.0f);
	clearLCD();
	renderTriangles();
	projectAllTriangles();
	delay_ms(50);
	while(1){

	}
	for(;;);
}
